### PR TITLE
Update to 1.16.5

### PR DESCRIPTION
**Pull request by Harleyoc1**
I love this mod so I decided to make all necessary changes to update it to 1.16. 

I've tested it with a few of the different config options and everything seems to be working fine. 

Update: As I’ve been unable to contact Lumien I’ve started my own [CurseForge project](https://www.curseforge.com/minecraft/mc-mods/chunkanimator) for this.

### CODE REVIEW

**Comment by Maurice2021** [comment]
Is there a new version to download ? best wishes from germany ^^

**Comment by Harleyoc1** [comment]
I'm hoping to get in contact with the original author so we can merge this and it can be uploaded to the original CurseForge page but it doesn't seem lumien is very active on GitHub any more. For now I could upload a build here I guess.

**Comment by Harleyoc1** [comment]
[1.16.5 Releases](https://www.curseforge.com/minecraft/mc-mods/chunkanimator/files)

Here's a build @Maurice2021. I know it works on its own but I haven't gotten around to testing it with other rendering mods yet so can't make any promises there.

**Comment by Maurice2021** [comment]
It works ! without Optifine but it works :D Thanks a lot, this is a little thing but it makes the game so much smoother ^^ thanks a lot ! 👍

**Comment by Harleyoc1** [comment]
I fixed the incompatibility with OptiFine and put a new build under the same message above.

**Comment by Maurice2021** [comment]
under the same message above ? so is the download link there the the fixed mod ?

**Comment by Harleyoc1** [comment]
> under the same message above ? so is the download link there the the fixed mod ? 

Yep, just click the same zip file in the message above (I edited it with the new file).

**Comment by Ajw2003** [comment]
is there any way to get this working with 1.16.4? I really want to use this on my server with a couple of my friends but 1.16.5 is a little too buggy rn for me

**Comment by Danadae** [comment]
> I fixed the incompatibility with OptiFine and put a new build under the same message above.

This mod is AMAZING, by far my favorite, and I really appreciate you updating it! I can't get it to work with Optifine  using Sildur's shaders though. Just an FYI

**Comment by Harleyoc1** [comment]
Thanks for all the feedback on this. Please could you redirect the issues to [this issue tracker](https://github.com/Harleyoc1/ChunkAnimator/issues) so I can more easily manage them. 

I think I made a mistake releasing a build on here, if I can’t get in contact with lumien in the next couple of days about merging and releasing this on the original CurseForge page then I will create a separate one for my fork.

**Comment by Harleyoc1** [comment]
> is there any way to get this working with 1.16.4? I really want to use this on my server with a couple of my friends but 1.16.5 is a little too buggy rn for me

And yes, this should work if I just allow 1.16.4 clients in the mods.toml (as there is such little difference between 1.16.4 and .5). I will try this in the next build (which I will release when I have a CurseForge page to upload to).

Update: For the time being I will release builds [here](https://github.com/Harleyoc1/ChunkAnimator/releases), allow me to test 1.16.4 before releasing a build for it though.

Another Update: Done, tested and [built](https://github.com/Harleyoc1/ChunkAnimator/releases/tag/1.16.5-pre-2). :)

**Comment by Danadae** [comment]
This is really awesome. I can't get it to work with my up to date forge/optifine & Vanillaplus shader but I'm probably doing something wrong. I'm just happy this mod is getting attention, and I hope you can get a CurseForge page up for it soon!

**Comment by Harleyoc1** [comment]
> This is really awesome. I can't get it to work with my up to date forge/optifine & Vanillaplus shader but I'm probably doing something wrong. I'm just happy this mod is getting attention, and I hope you can get a CurseForge page up for it soon!

Yep I'll take a look at the shaders problem next. Do you know if it breaks with any shares or is a couple of specific ones causing problems?

**Comment by Danadae** [comment]
The only shaders I've used are Sildur's, BSL, and Vanillaplus, and it doesn't work with those. I reckon it's a shader problem in general? Not sure.

**Comment by Harleyoc1** [comment]
@Danadae That’s odd. I just installed Sildur’s (medium) and it seems to be working fine for me. What exactly is the problem? Is there a crash or are the chunks just not being animated for you?

**Comment by Danadae** [comment]
I also used Sildur's medium and light. It's possible I'm doing something wrong, the game does not crash and seems to run fine, the chunks just aren't animating. I'm using the latest version of Forge and Optifine, and everything else is up to date, drivers ect. I've placed the optifine .jar file and your newest .jar file in the mods folder and I'm using the regular game launcher to select Forge and start the game. I tinkered around with the settings in optifine too just to see if something was blocking it but nothing changed. Does that help?

**Comment by Harleyoc1** [comment]
@Danadae Yes but I just don’t understand how it could be working for me and not for you. It shouldn’t effect this but are you definitely on [pre-release 2](https://github.com/Harleyoc1/ChunkAnimator/releases/tag/1.16.5-pre-2)? It’s possible I changed something between the build I put above in the zip (if you are using that still) and pre release 1 that might have somehow fixed it.

**Comment by Danadae** [comment]
Yes, I'm certain I downloaded the correct one (I downloaded it several times to be sure).

**Comment by Harleyoc1** [comment]
How strange. I’ll test the other shader packs you listed above and see if I can reproduce the issue. Without being able to debug it myself there’s not a lot I can do about it.

**Comment by Harleyoc1** [comment]
Nope. All three shaders you listed above work perfectly fine with it for me. @Danadae Have you tried running it with no other mods enabled other than chunk animator and OptiFine, I don’t see how that could be the issue but worth a shot I guess.

**Comment by Danadae** [comment]
> @Danadae Have you tried running it with no other mods enabled other than chunk animator and OptiFine

I've tried exactly this, after a fresh install of EVERYTHING. Minceraft, Forge, then re-downloaded Optifine, Vanillaplus Shaders and your file, drivers updated, and still no chunk animation when using Optifine and Chunk Animator together. Chunk Animator alone works fine, but as soon as I put the Optifine .jar in the mod folder and restart the game it stops working. Really odd, right?

**Comment by Harleyoc1** [comment]
Wait back up a second, your problem is with OptiFine, even without shaders?

**Comment by Danadae** [comment]
I think so. Using Forge the Chunk Animator works fine until I introduce the Optifine .jar file into the mods folder. At that point Optifine kicks in and the chunk animation stops working, even if I turn the shaders off.

**Comment by Harleyoc1** [comment]
Can you confirm the OptiFine and Forge versions you are running?

**Comment by Danadae** [comment]
Sure:


OptiFine:  Forge 36.0.0 | 16.01.2021 , File: OptiFine_1.16.5_HD_U_G6.jar
Forge 36.0.30

**Comment by Harleyoc1** [comment]
Yeah I’ve tested on that OptiFine (and assuming nothing broke between 36.0.26 and 36.0.30 but that was the latest when I tested it).

**Comment by Harleyoc1** [comment]
@Danadae You definitely downloaded [this](https://github.com/Harleyoc1/Chunk-Animator/releases/tag/1.16.5-pre-2) exact file? Just making sure because I don’t really know what else to suggest...

**Comment by Danadae** [comment]
Yep, more than once. Pretty odd, I wonder if it's just me?

**Comment by Harleyoc1** [comment]
I just got a friend to test this out for me and it works for them too, so I’ve no idea what’s causing it but seems it’s something on your end.

**Comment by Danadae** [comment]
I'm going to give everything one more try with a fresh install when I get home later. I'll give you an update as to what happens. I did mention that I'm using the normal game launcher to select Forge and start the game, yes?

**Comment by NuclearTyrant** [comment]
hm, I seem to be having the same problem as Danadae, i thought it was because i had Optiforge installed, (a mod that allows compatibility between forge and Optifine, before official compatibility) but this wasn't the case, i also have ChunkAnimator-MC1.16.5-1.2-PRE-2.jar installed and OptiFine_1.16.5_HD_U_G6.jar as well, as well as testing with and without Optiforge, my forge version is 36.0.22.

**Comment by Harleyoc1** [comment]
Very strange. As I’ve said above there’s nothing I can really do unless I’m able to reproduce this myself. 

I guess I could create you a temporary “debug” version with some extra logging or something like that.

**Comment by Harleyoc1** [comment]
@Danadae @NuclearTyrant do either of you have `ofRenderRegions` set to true in the config (`optionsof.txt` in your minecraft folder or I believe it’s under performance in the video settings GUI)? It renders chunks in a different way so it could be causing the problem if you have it enabled (in fact if you do have it enabled I would not expect it to work at all).

**Comment by Danadae** [comment]
Had to head out for a bit, as soon as I get home I'll check on this and let you know. Really appreciate you putting effort into getting this mod to work, it's one of the most aesthetically pleasing ones available.

**Comment by NuclearTyrant** [comment]
@Harleyoc1 i am currently checking on that render regions idea

**Comment by NuclearTyrant** [comment]
That was the exact problem, its working now, for me at least, thank you so much!

**Comment by Danadae** [comment]
> @Danadae @NuclearTyrant do either of you have `ofRenderRegions` set to true in the config (`optionsof.txt` in your minecraft folder or I believe it’s under performance in the video settings GUI)? It renders chunks in a different way so it could be causing the problem if you have it enabled (in fact if you do have it enabled I would not expect it to work at all).

IT WORKS! Setting that option to "false" fixed the issue! THANK YOU SO MUCH!

**Comment by Harleyoc1** [comment]
It has been a few days now with no response from lumien, so I’m going to close this PR and create a new CurseForge page for my fork. 

I will be taking feature requests and bug reports for all versions, so if you’d like to see a new feature in the 1.12 version or are getting a bug in it please do report it on my fork and I’ll take a look at it.

**Pull request closed without merging**
